import styles from "./chest.module.css";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AnKr | Chest",
  description: "Generated by create next app",
};

async function getData() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
    next: {
      revalidate: 60,
    },
  });
  if (!response.status) throw new Error(`${response.status}`);
  return response.json();
}

export default async function Chest() {
  const posts = await getData();
  console.log(posts);

  return (
    <div className={styles.general}>
      {posts.map((el: any) => {
        return (
          <Link
            className={styles.glowonhover}
            key={el.id}
            href={`/chest/${el.id}`}
          >
            {el.id}
          </Link>
        );
      })}
    </div>
  );
}
