import { Header } from "@/components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/components/Footer/Footer";
import { Metadata } from "next";

const Noto_Sans = Inter();

export const metadata: Metadata = {
  title: "AnKr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Noto_Sans.className}>
        <Header />
        <main className="container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
