"use client";
import { Metadata } from "next";
import React from "react";
import styles from "./user.module.css";
import Link from "next/link";
import { useNight } from "@/store";

export const metadata: Metadata = {
  title: "Ankr | User",
  description: "Generated by create next app",
};
export default function User() {
  const { night } = useNight();
  return (
    <div className={night ? styles.general : styles.generalDay}>
      <h1>Krasikov Anton </h1>
      <h2>frontend developer</h2>
      <p>Skills:</p>
      <ul className={styles.ul}>
        <li>HTML</li>
        <li>CSS</li>
        <li>JavaScript</li>
        <li>React</li>
        <li>Next</li>
        <li>Nest</li>
        <li>Redux</li>
        <li>Redux Toolkit</li>
        <li>React-Router</li>
        <li>Redux-Thunk</li>
        <li>Yup</li>
        <li>Formik</li>
        <li>Figma</li>
      </ul>
      <Link href="https://t.me/ttttttttue">contact me</Link>
    </div>
  );
}
